### ISSUE TITLE
merge gond

### ISSUE THREAD

**Issue by mrzealot** [ktorpi/TGcommander#4]
Nemtom ti hogy vagytok vele, de én a brencseléshez meg a merge-léshez nem nagyon értek, úgyhogy csak annyit szeretnék kérni, hogy ne pussoljatok már semmit légyszi, amíg haza nem érek!!!
Van megint egy valag módosításom, előbb az mennyen be. Aztán majd utána nézünk, hogy ezt elegánsan hogy is kellene...
Thx

**Comment by ktorpi** [comment]
git pull/push origin mastert írj, ha olyan hibát ir, hogy nemtudja hogy hova mergeljen!
